# Generated by Django 4.0.3 on 2022-03-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habr_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(default='qwe', verbose_name='url'),
        ),
    ]
