# Generated by Django 4.0.3 on 2022-03-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habr_parser', '0002_article_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
    ]
