# Generated by Django 4.0.3 on 2022-03-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habr_parser', '0003_alter_article_options_rename_link_article_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор Статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(default='qwe', verbose_name='url статьи'),
        ),
    ]
